# This is a basic workflow to help you get started with Actions

name: Master Branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar  
          
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Maven package
        run: mvn clean package --file pom.xml
        
      - name: Unit Test
        run: mvn test --file pom.xml
        
      - name: SonarQube scan
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.organization=iamabhi365
          -Dsonar.projectKey=iamabhi365_devops-homework
        env: 
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Docker repo login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: iamabhi365/devops-homework:${{ github.run_number }}
        env:
         REPO: ${{ secrets.DOCKER_REPO }}

      - name: Update Tag
        env:
           IMAGE_VERSION: ${{ github.run_number }} 
        run: |
          sed "s/IMAGE_VERSION/$IMAGE_VERSION/g"  checkweather.yaml > updated_image.yaml
          cat updated_image.yaml

      - name: Create deployment
        uses: Eyevinn/action-eks-kubectl@master
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            IMAGE_VERSION: ${{ github.run_number }}          
            REGION: us-east-2
            CLUSTER: devops-homework
        with:
          args: apply -f updated_image.yaml
          
      - name: Get service list 
        uses: Eyevinn/action-eks-kubectl@master
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            REGION: us-east-2
            CLUSTER: devops-homework
        with:
          args: get  svc
